<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit

$namespace = 'charityroot';
$rootpath = 'src/';
$fileinfos = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($rootpath)
);
$files = [];
foreach($fileinfos as $pathname => $fileinfo) {
    if (!$fileinfo->isFile()) continue;
    $path = str_replace($rootpath, '', $pathname);
    $parts = rtrim($path, '.php');
    $parts = ltrim($parts, '/');
    $parts = str_replace('.', '', $parts);
    $parts = str_replace('.', '', $parts);

    $explode = explode('/', $parts);
    if (count($explode) === 3) {
        $parts = str_replace($explode[1].'/', '', $parts);
    }

    $parts = str_replace('shipwire/', $namespace .'\\'.'\\', $parts);
    if ($parts == 'shipwire') {
        $parts = 'charityroot\\\shipwire';
    }

    $files[$parts] = '/src/' . $path;
}
print_r($files);exit;
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = $files;
        }

        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
